#!/bin/bash
# Quick start scripts for Ghidra MCP Integration Suite

echo "=== Ghidra MCP Integration Suites ==="
echo ""
echo "1. 🚀 LaurieWired MCP Server (Primary - Ready to use)"
echo "   Simple, fast, works without Maven build"
echo ""
echo "Start MCP server:"
echo "  cd /root/tools/GhidraMCP-Laurie && source .venv/bin/activate && python bridge_mcp_ghidra.py"
echo ""
echo "Or with HTTP transport (for web clients):"
echo "  cd /root/tools/GhidraMCP-Laurie && source .venv/bin/activate && python bridge_mcp_ghidra.py --transport sse --mcp-port 8081"
echo ""
echo "2. 🔧 Bethington MCP Server (Build needed)"
echo "   Production-grade with 267+ tools, requires Maven build"
echo ""
echo "Status: ⚠️ Requires Maven build + Ghidra 12.1.2 compatibility"
echo "   Current system has Ghidra 11.4.3 and JDK 21"
echo ""
echo "3. 💻 Rizin rz-ghidra Plugin (Lightweight)"
echo "   Standalone decompiler via Rizin framework"
echo ""
echo "Install first: sudo apt install rizin cmake make"
echo "Then: rizin binary && pdg (decompile current function)"
echo ""
